name: Narative Game CI/CD Pipeline
run-name: CI/CD Narrative Game

on:
  push:
    branches:  
      - main
      - story-visuals
  pull_request:
    branches:  
      - main
      - story-visuals

jobs:
  Run-Python-test-scripts:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
      
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python Decision test script
        run: |
          python -m unittest TestCases.py > test.txt
      
      - name: Run python P2PNetwork methods test script
        run: |
         python -m unittest testP2PNetwork.py >> test.txt

      - name: Run python  Game Hosting and Joining Connections test script
        run: |
          python -m unittest testHostingJoiningConnections.py >> test.txt
        
      - name: Run Security Audit
        if: github.event_name == 'push' && github.ref == 'refs/head/main'
        run: |
          pip install pip-audit
          pip-audit


      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test.txt
        