name: Narative Game workflow
run-name: Testing Github Actions for Python script

on:
  push:
    branches:  
      - main
      - story-visuals
  pull_request:
    branches:  
      - main
      - story-visuals

jobs:
  trail-python-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
      
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          pip install playsound==1.2.2

          
      - name: Set up virtual display
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -ac &
          export DISPLAY=:99

      - name: Run python Decision test script
        run: |
          python -m unittest discover
      
     # - name: Run python ImageHandler test script
     #   run: |
     #     python -m unittest TestImageHandler.py