name: Narative Game workflow
run-name: CI/CD Narrative Game

on:
  push:
    branches:  
      - main
      - story-visuals
  pull_request:
    branches:  
      - main
      - story-visuals

jobs:
  Run-Python-test-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
      
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python Decision test script
        run: |
          python -m unittest TestCases.py
      
      - name: Run python P2PNetwork methods test script
        run: |
         python -m unittest testP2PNetwork.py
      - name: Run python  Game Hosting and Joining Connections test script
        run: |
          python -m unittest testHostingJoiningConnections.py
      
      - name: Run python  Image Display test script
        run: |
          python -m unittest TestImageHandler.py